HouseRentingSystem/Controllers/HouseController.cs
using HouseRentingSystem.Contract.Agent;
using HouseRentingSystem.Contract.House;
using HouseRentingSystem.Infrastructure;
using HouseRentingSystem.Models.Houses;
using HouseRentingSystem.Services.House;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Controllers
{

    [Authorize]
    public class HouseController : Controller
    {

        private readonly IHouseService _houses;
        private readonly IAgentService _agents;
        public HouseController(IHouseService houses, IAgentService agent)
        {
                _houses = houses;
                _agents = agent;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllHousesQueryModel query)
        {
            var queryResult = _houses.All(
                query.Category,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllHousesQueryModel.HousesPerPage
                );

            query.TotalHouseCount = queryResult.TotalHouseCount;
            query.Houses = queryResult.Houses;

            var houseCategories = await _houses.AllCategoriesName();
            query.Categories = (IEnumerable<string>)houseCategories;

            return View(query);
        }

        [HttpPost]
        public async Task<IActionResult> All(HouseFormModel model)
        {
            return RedirectToAction(nameof(Details), new { id = "1" });
        }


        [AllowAnonymous]
        public async Task<IActionResult> Add()
        {
            if (await _agents.ExistsById(User.Id()) == false)
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            };
            return View(new HouseFormModel
            {
                Categories = await _houses.AllCategories()
            });

        }
        [HttpPost]
        public async Task<IActionResult> Add(HouseFormModel model)
        {
            if (await _agents.ExistsById(User.Id()) == false)
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            };
            if (await _houses.CategoryExists(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Категорията не съществува");
            }
            if (!ModelState.IsValid)
            {
                model.Categories = await _houses.AllCategories();
                return View(model);
            }
            var agentId = await _agents.GetAgentId(User.Id());
            var newHouseId = await _houses.Create(model.Title, model.Address, model.Description,
                    model.ImageUrl, model.PricePerMonth, model.CategoryId, agentId);

            return RedirectToAction(nameof(Details), new {Id = newHouseId});

        }
        public async Task<IActionResult> Mine()
        {
            return View(new AllHousesQueryModel());
        }
        public async Task<IActionResult> Details(int id)
        {
            return View(new HouseDetailsViewModel());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(new HouseFormModel());
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, HouseFormModel house)
        {
            return RedirectToAction(nameof(Details), new { id = "1" });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return View(new HouseFormModel());
        }

        [HttpPost]
        public async Task<IActionResult> Dekete(HouseDetailsViewModel house)
        {
            return RedirectToAction(nameof(All));
        }

        //[HttpPost]
        //public async Task<IActionResult> Rent(int id)
        //{
        //    return RedirectToAction(nameof(Mine));
        //}

        //[HttpPost]
        //public async Task<IActionResult> Leave(int id)
        //{
        //    return RedirectToAction(nameof(Mine));
        //}

    }
}

HouseRentingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best House System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HouseRentingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">House Renting WorldWide</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="All">All Houses</a>
                        </li>
                        @if(this.User.Identity.IsAuthenticated){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Mine">My Houses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Add">Add Houses</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;  @DateTime.Now.Year - HouseRentingSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>